export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const UPDATE_PASSWORD_REQUEST = 'UPDATE_PASSWORD_REQUEST';
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS';
export const UPDATE_PASSWORD_FAILURE = 'UPDATE_PASSWORD_FAILURE';

export const FECTH_USER_DATA = 'FECTH_USER_DATA';
export const FETCH_USER_TEAM = 'FETCH_USER_TEAM';


export const FETCH_HOME_EVENTS = 'FETCH_USER_EVENTS';
export const FETCH_EVENT_LIKES = 'FETCH_EVENT_LIKES';
export const FETCH_HANDLE_ERROR = 'FETCH_HANDLE_ERROR';

export const EVENT_LIKE = 'EVENT_LIKE';
export const EVENT_UNLIKE = 'EVENT_UNLIKE';

export const FETCH_BRANCH = 'FETCH_BRANCH';
export const FETCH_BRANCH_FAILED = 'FETCH_BRANCH_FAILED';

export const POST_EVENT_START = 'POST_EVENT_START';
export const POST_EVENT_SUCCESS = 'POST_EVENT_SUCCESS';
export const POST_EVENT_FAILED = 'POST_EVENT_FAILED';

export const DELETE_EVENT_POST = 'DELETE_EVENT_POST';
export const FETCH_EVENT_TO_EDIT = 'FETCH_EVENT_TO_EDIT'
